# Generated by Django 3.0.3 on 2020-02-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_auto_20200227_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='intoresume',
            name='d_resume_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='intoresume',
            name='d_resume_dob',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
