# Generated by Django 3.0.3 on 2020-02-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_auto_20200228_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='intoresume',
            name='d_resume_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
