# Generated by Django 3.0.3 on 2020-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0061_auto_20200228_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intoresume',
            name='d_resume_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
