# Generated by Django 2.2 on 2020-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_auto_20200228_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
