# Generated by Django 2.2 on 2020-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_contactdbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdbs',
            name='email',
            field=models.CharField(default='xyz', max_length=300),
        ),
        migrations.AddField(
            model_name='contactdbs',
            name='message',
            field=models.CharField(default='ffffff', max_length=300),
        ),
        migrations.AddField(
            model_name='contactdbs',
            name='name',
            field=models.CharField(default='xyz', max_length=300),
        ),
        migrations.AddField(
            model_name='contactdbs',
            name='subject',
            field=models.CharField(default='xyz', max_length=300),
        ),
    ]
