# Generated by Django 3.0.7 on 2020-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0064_auto_20200730_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended',
            name='hired',
            field=models.BooleanField(default=False),
        ),
    ]
