# Generated by Django 2.2 on 2020-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_messeges'),
    ]

    operations = [
        migrations.AddField(
            model_name='intoresume',
            name='d_resume_status',
            field=models.BooleanField(default=True),
        ),
    ]
