# Generated by Django 2.2 on 2020-08-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_intoresume_d_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recommend_request',
            field=models.BooleanField(default=False),
        ),
    ]
