# Generated by Django 2.2 on 2020-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_job_recommend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='request_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
