# Generated by Django 2.2 on 2020-08-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_remove_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Pgender',
            field=models.CharField(max_length=15),
        ),
    ]
